import {approvePaymentRequest, assignVendorProject, createApartment, createEstate, createFacilityManager, createMemberForOrganization, createOfflineServiceChargePaymentForResident, createOrganization, createPaymentForEstate, createPaymentRequestForEstate, createProject, createVendor, fetchAllApartment, fetchAllEstate, fetchAllFacilityManager, fetchAllProject, fetchAllVendor, fetchApartmentById, fetchApartmentsByEstate, fetchCurrentApartment, fetchCurrentFacilityManager, fetchCurrentMember, fetchCurrentOrganization, fetchCurrentVendor, fetchEstateById, fetchEstatesByFacilityManager, fetchEstatesByOrganization, fetchFacilityManagerByEstate, fetchFacilityManagerById, fetchFacilityManagerEstatesByFacilityManager, fetchMemberById, fetchOrganizationById, fetchPaymentRequestById, fetchPaymentRequestsByEstate, fetchPaymentRequestsByMember, fetchPaymentRequestsByOrganization, fetchPaymentsByEstate, fetchPaymentsByResident, fetchProjectById, fetchProjectsByEstate, fetchProjectsByFacilityManager, fetchProjectsByResident, fetchProjectsByVendor, fetchPublicProjectsByEstate, fetchVendorById, fetchVendorsByEstate, fetchWithdrawalsByWithdrawal, inviteMemberForOrganization, makePaymentProject, rejectPaymentRequest, updateApartment, updateCommissionEstate, updateEstate, updateFacilityManagerEstate, updateOrganization, updatePaymentLimitMember, updatePermissionsMember, updateRoleMember, updateServicesEstate, updateStatusProject, updateVendorsEstate} from '../thunks';
import {createSlice, isAnyOf} from '@reduxjs/toolkit';

import facilityManagersAdapter from '../adapters/facility-manager';

export const facilityManagersSlice = createSlice({
    name: 'facilityManagers',
    initialState: facilityManagersAdapter.getInitialState(),
    reducers: {},
    extraReducers: (builder) => {
        builder.addMatcher(isAnyOf(approvePaymentRequest.fulfilled, assignVendorProject.fulfilled, createApartment.fulfilled, createEstate.fulfilled, createFacilityManager.fulfilled, createMemberForOrganization.fulfilled, createOfflineServiceChargePaymentForResident.fulfilled, createOrganization.fulfilled, createPaymentForEstate.fulfilled, createPaymentRequestForEstate.fulfilled, createProject.fulfilled, createVendor.fulfilled, fetchAllApartment.fulfilled, fetchAllEstate.fulfilled, fetchAllFacilityManager.fulfilled, fetchAllProject.fulfilled, fetchAllVendor.fulfilled, fetchApartmentById.fulfilled, fetchApartmentsByEstate.fulfilled, fetchCurrentApartment.fulfilled, fetchCurrentFacilityManager.fulfilled, fetchCurrentMember.fulfilled, fetchCurrentOrganization.fulfilled, fetchCurrentVendor.fulfilled, fetchEstateById.fulfilled, fetchEstatesByFacilityManager.fulfilled, fetchEstatesByOrganization.fulfilled, fetchFacilityManagerByEstate.fulfilled, fetchFacilityManagerById.fulfilled, fetchFacilityManagerEstatesByFacilityManager.fulfilled, fetchMemberById.fulfilled, fetchOrganizationById.fulfilled, fetchPaymentRequestById.fulfilled, fetchPaymentRequestsByEstate.fulfilled, fetchPaymentRequestsByMember.fulfilled, fetchPaymentRequestsByOrganization.fulfilled, fetchPaymentsByEstate.fulfilled, fetchPaymentsByResident.fulfilled, fetchProjectById.fulfilled, fetchProjectsByEstate.fulfilled, fetchProjectsByFacilityManager.fulfilled, fetchProjectsByResident.fulfilled, fetchProjectsByVendor.fulfilled, fetchPublicProjectsByEstate.fulfilled, fetchVendorById.fulfilled, fetchVendorsByEstate.fulfilled, fetchWithdrawalsByWithdrawal.fulfilled, inviteMemberForOrganization.fulfilled, makePaymentProject.fulfilled, rejectPaymentRequest.fulfilled, updateApartment.fulfilled, updateCommissionEstate.fulfilled, updateEstate.fulfilled, updateFacilityManagerEstate.fulfilled, updateOrganization.fulfilled, updatePaymentLimitMember.fulfilled, updatePermissionsMember.fulfilled, updateRoleMember.fulfilled, updateServicesEstate.fulfilled, updateStatusProject.fulfilled, updateVendorsEstate.fulfilled), (state, action) => {
            facilityManagersAdapter.upsertMany(state, action.payload.entities.facilityManagers);
        });
    },
});

export const facilityManagersReducer = facilityManagersSlice.reducer;

export const facilityManagersActions = facilityManagersSlice.actions;