import {approvePaymentRequest, assignVendorProject, createApartment, createApartmentType, createEstate, createOfflineServiceChargePaymentForResident, createPaymentForEstate, createPaymentRequestForEstate, createProject, createServiceCategory, createVendor, fetchAllApartment, fetchAllApartmentType, fetchAllEstate, fetchAllProject, fetchAllVendor, fetchApartmentById, fetchApartmentTypeById, fetchApartmentsByEstate, fetchCurrentApartment, fetchCurrentVendor, fetchEstateById, fetchEstatesByFacilityManager, fetchEstatesByOrganization, fetchFacilityManagerEstatesByFacilityManager, fetchPaymentRequestById, fetchPaymentRequestsByEstate, fetchPaymentRequestsByMember, fetchPaymentRequestsByOrganization, fetchPaymentsByEstate, fetchPaymentsByResident, fetchProjectById, fetchProjectsByEstate, fetchProjectsByFacilityManager, fetchProjectsByResident, fetchProjectsByVendor, fetchPublicProjectsByEstate, fetchRecurringPaymentsByEstate, fetchServiceCategory, fetchVendorById, fetchVendorsByEstate, fetchWithdrawalsByWithdrawal, makePaymentProject, rejectPaymentRequest, updateApartment, updateApartmentType, updateCommissionEstate, updateEstate, updateFacilityManagerEstate, updateServiceChargeApartmentType, updateServicesApartmentType, updateServicesEstate, updateStatusProject, updateVendorsEstate} from '../thunks';
import {createSlice, isAnyOf} from '@reduxjs/toolkit';

import serviceCategoriesAdapter from '../adapters/service-category';

export const serviceCategoriesSlice = createSlice({
    name: 'serviceCategories',
    initialState: serviceCategoriesAdapter.getInitialState(),
    reducers: {},
    extraReducers: (builder) => {
        builder.addMatcher(isAnyOf(approvePaymentRequest.fulfilled, assignVendorProject.fulfilled, createApartment.fulfilled, createApartmentType.fulfilled, createEstate.fulfilled, createOfflineServiceChargePaymentForResident.fulfilled, createPaymentForEstate.fulfilled, createPaymentRequestForEstate.fulfilled, createProject.fulfilled, createServiceCategory.fulfilled, createVendor.fulfilled, fetchAllApartment.fulfilled, fetchAllApartmentType.fulfilled, fetchAllEstate.fulfilled, fetchAllProject.fulfilled, fetchAllVendor.fulfilled, fetchApartmentById.fulfilled, fetchApartmentTypeById.fulfilled, fetchApartmentsByEstate.fulfilled, fetchCurrentApartment.fulfilled, fetchCurrentVendor.fulfilled, fetchEstateById.fulfilled, fetchEstatesByFacilityManager.fulfilled, fetchEstatesByOrganization.fulfilled, fetchFacilityManagerEstatesByFacilityManager.fulfilled, fetchPaymentRequestById.fulfilled, fetchPaymentRequestsByEstate.fulfilled, fetchPaymentRequestsByMember.fulfilled, fetchPaymentRequestsByOrganization.fulfilled, fetchPaymentsByEstate.fulfilled, fetchPaymentsByResident.fulfilled, fetchProjectById.fulfilled, fetchProjectsByEstate.fulfilled, fetchProjectsByFacilityManager.fulfilled, fetchProjectsByResident.fulfilled, fetchProjectsByVendor.fulfilled, fetchPublicProjectsByEstate.fulfilled, fetchRecurringPaymentsByEstate.fulfilled, fetchServiceCategory.fulfilled, fetchVendorById.fulfilled, fetchVendorsByEstate.fulfilled, fetchWithdrawalsByWithdrawal.fulfilled, makePaymentProject.fulfilled, rejectPaymentRequest.fulfilled, updateApartment.fulfilled, updateApartmentType.fulfilled, updateCommissionEstate.fulfilled, updateEstate.fulfilled, updateFacilityManagerEstate.fulfilled, updateServiceChargeApartmentType.fulfilled, updateServicesApartmentType.fulfilled, updateServicesEstate.fulfilled, updateStatusProject.fulfilled, updateVendorsEstate.fulfilled), (state, action) => {
            serviceCategoriesAdapter.upsertMany(state, action.payload.entities.serviceCategories);
        });
    },
});

export const serviceCategoriesReducer = serviceCategoriesSlice.reducer;

export const serviceCategoriesActions = serviceCategoriesSlice.actions;